-- Migration: Create comprehensive stock symbols table
-- This contains top 500 Indian stocks for search and watchlist functionality

-- 1. Stock Symbols Table
CREATE TABLE IF NOT EXISTS stock_symbols (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol TEXT NOT NULL UNIQUE,      -- NSE symbol like RELIANCE
    name TEXT NOT NULL,               -- Full company name
    sector TEXT,                      -- IT, Banking, Energy, etc.
    industry TEXT,                    -- Sub-sector
    exchange TEXT DEFAULT 'NSE',      -- NSE, BSE
    market_cap_category TEXT,         -- Large, Mid, Small cap
    is_active BOOLEAN DEFAULT TRUE,
    isin_code TEXT,                   -- ISIN for unique identification
    metadata JSONB,                   -- Extra data
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for fast search
CREATE INDEX IF NOT EXISTS idx_stock_symbols_symbol ON stock_symbols(symbol);
CREATE INDEX IF NOT EXISTS idx_stock_symbols_name ON stock_symbols(name);
CREATE INDEX IF NOT EXISTS idx_stock_symbols_sector ON stock_symbols(sector);
CREATE INDEX IF NOT EXISTS idx_stock_symbols_active ON stock_symbols(is_active);

-- Full-text search index
CREATE INDEX IF NOT EXISTS idx_stock_symbols_search ON stock_symbols 
    USING gin(to_tsvector('english', coalesce(symbol, '') || ' ' || coalesce(name, '')));

-- 2. User Watchlist Table (for personalized tracking)
CREATE TABLE IF NOT EXISTS user_watchlist (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID DEFAULT '00000000-0000-0000-0000-000000000000'::UUID,  -- Default user for now
    stock_symbol TEXT NOT NULL REFERENCES stock_symbols(symbol) ON DELETE CASCADE,
    added_at TIMESTAMPTZ DEFAULT now(),
    priority INTEGER DEFAULT 5,       -- User-defined priority (1-10)
    notes TEXT,                     -- User notes
    is_active BOOLEAN DEFAULT TRUE,
    UNIQUE(user_id, stock_symbol)
);

CREATE INDEX IF NOT EXISTS idx_user_watchlist_user ON user_watchlist(user_id);
CREATE INDEX IF NOT EXISTS idx_user_watchlist_symbol ON user_watchlist(stock_symbol);
CREATE INDEX IF NOT EXISTS idx_user_watchlist_priority ON user_watchlist(priority DESC);

-- 3. Populate with Top NSE Stocks (Nifty 500 subset - prioritizing liquid stocks)
WITH src AS (
  SELECT DISTINCT ON (v.symbol)
    v.symbol, v.name, v.sector, v.industry, v.market_cap_category, v.isin_code
  FROM (VALUES
    -- paste your rows here as (symbol, name, sector, industry, market_cap_category, isin_code)
    ('RELIANCE', 'Reliance Industries Ltd', 'Energy', 'Oil & Gas - Refining & Marketing', 'Large', 'INE002A01018'),
('TCS', 'Tata Consultancy Services Ltd', 'IT', 'IT Services & Consulting', 'Large', 'INE467B01029'),
('HDFCBANK', 'HDFC Bank Ltd', 'Financial Services', 'Private Banks', 'Large', 'INE040A01034'),
('INFY', 'Infosys Ltd', 'IT', 'IT Services & Consulting', 'Large', 'INE009A01021'),
('ICICIBANK', 'ICICI Bank Ltd', 'Financial Services', 'Private Banks', 'Large', 'INE090A01021'),
('HINDUNILVR', 'Hindustan Unilever Ltd', 'Consumer Staples', 'FMCG - Household Products', 'Large', 'INE030A01027'),
('SBIN', 'State Bank of India', 'Financial Services', 'Public Banks', 'Large', 'INE062A01020'),
('BHARTIARTL', 'Bharti Airtel Ltd', 'Telecom', 'Telecom - Cellular & Fixed Line', 'Large', 'INE397D01024'),
('ITC', 'ITC Ltd', 'Consumer Staples', 'FMCG - Cigarettes & Tobacco', 'Large', 'INE154A01025'),
('KOTAKBANK', 'Kotak Mahindra Bank Ltd', 'Financial Services', 'Private Banks', 'Large', 'INE237A01028'),
('BAJFINANCE', 'Bajaj Finance Ltd', 'Financial Services', 'NBFC - Consumer Finance', 'Large', 'INE296A01024'),
('L&T', 'Larsen & Toubro Ltd', 'Construction', 'Construction - Diversified', 'Large', 'INE018A01030'),
('HCLTECH', 'HCL Technologies Ltd', 'IT', 'IT Services & Consulting', 'Large', 'INE860A01027'),
('ASIANPAINT', 'Asian Paints Ltd', 'Consumer Discretionary', 'Paints & Varnishes', 'Large', 'INE021A01026'),
('AXISBANK', 'Axis Bank Ltd', 'Financial Services', 'Private Banks', 'Large', 'INE238A01034'),
('MARUTI', 'Maruti Suzuki India Ltd', 'Consumer Discretionary', 'Passenger Cars', 'Large', 'INE585B01010'),
('SUNPHARMA', 'Sun Pharmaceutical Industries Ltd', 'Healthcare', 'Pharmaceuticals', 'Large', 'INE044A01036'),
('TITAN', 'Titan Company Ltd', 'Consumer Discretionary', 'Retail - Jewellery', 'Large', 'INE280A01028'),
('ULTRACEMCO', 'UltraTech Cement Ltd', 'Construction', 'Cement & Cement Products', 'Large', 'INE481G01011'),
('NESTLEIND', 'Nestle India Ltd', 'Consumer Staples', 'FMCG - Foods', 'Large', 'INE239A01024'),
('WIPRO', 'Wipro Ltd', 'IT', 'IT Services & Consulting', 'Large', 'INE075A01022'),
('POWERGRID', 'Power Grid Corporation of India Ltd', 'Energy', 'Power - Transmission', 'Large', 'INE752E01010'),
('NTPC', 'NTPC Ltd', 'Energy', 'Power Generation', 'Large', 'INE733E01010'),
('M&M', 'Mahindra & Mahindra Ltd', 'Consumer Discretionary', 'Passenger Cars & UVs', 'Large', 'INE101A01026'),
('TECHM', 'Tech Mahindra Ltd', 'IT', 'IT Services & Consulting', 'Large', 'INE669C01036'),
('ADANIENT', 'Adani Enterprises Ltd', 'Diversified', 'Diversified', 'Large', 'INE423A01024'),
('ADANIPORTS', 'Adani Ports and Special Economic Zone Ltd', 'Services', 'Port & Port Services', 'Large', 'INE742F01042'),
('GRASIM', 'Grasim Industries Ltd', 'Construction', 'Cement & Cement Products', 'Large', 'INE047A01021'),
('CIPLA', 'Cipla Ltd', 'Healthcare', 'Pharmaceuticals', 'Large', 'INE059A01026'),
('TATAMOTORS', 'Tata Motors Ltd', 'Consumer Discretionary', 'Passenger Cars & UVs', 'Large', 'INE155A01022'),
('DRREDDY', 'Dr Reddys Laboratories Ltd', 'Healthcare', 'Pharmaceuticals', 'Large', 'INE089A01023'),
('EICHERMOT', 'Eicher Motors Ltd', 'Consumer Discretionary', '2/3 Wheelers', 'Large', 'INE066A01021'),
('JSWSTEEL', 'JSW Steel Ltd', 'Metals & Mining', 'Iron & Steel', 'Large', 'INE019A01038'),
('HINDALCO', 'Hindalco Industries Ltd', 'Metals & Mining', 'Aluminium & Aluminium Products', 'Large', 'INE038A01020'),
('DIVISLAB', 'Divis Laboratories Ltd', 'Healthcare', 'Pharmaceuticals', 'Large', 'INE361B01024'),
('SBILIFE', 'SBI Life Insurance Company Ltd', 'Financial Services', 'Life Insurance', 'Large', 'INE123W01016'),
('HDFCLIFE', 'HDFC Life Insurance Company Ltd', 'Financial Services', 'Life Insurance', 'Large', 'INE795G01014'),
('TATACONSUM', 'Tata Consumer Products Ltd', 'Consumer Staples', 'FMCG - Foods', 'Large', 'INE192A01025'),
('BPCL', 'Bharat Petroleum Corporation Ltd', 'Energy', 'Oil & Gas - Refining & Marketing', 'Large', 'INE029A01011'),
('BRITANNIA', 'Britannia Industries Ltd', 'Consumer Staples', 'FMCG - Foods', 'Large', 'INE216A01030'),
('APOLLOHOSP', 'Apollo Hospitals Enterprise Ltd', 'Healthcare', 'Healthcare - Hospital Services', 'Large', 'INE437A01024'),
('UPL', 'UPL Ltd', 'Chemicals', 'Agrochemicals', 'Large', 'INE628A01036'),
('SHREECEM', 'Shree Cement Ltd', 'Construction', 'Cement & Cement Products', 'Large', 'INE070A01015'),
('HEROMOTOCO', 'Hero MotoCorp Ltd', 'Consumer Discretionary', '2/3 Wheelers', 'Large', 'INE158A01026'),
('ONGC', 'Oil & Natural Gas Corporation Ltd', 'Energy', 'Oil & Gas - Exploration & Production', 'Large', 'INE213A01029'),
('COALINDIA', 'Coal India Ltd', 'Metals & Mining', 'Coal & Lignite', 'Large', 'INE522F01014'),
('BAJAJ-AUTO', 'Bajaj Auto Ltd', 'Consumer Discretionary', '2/3 Wheelers', 'Large', 'INE917I01010'),
('INDUSINDBK', 'IndusInd Bank Ltd', 'Financial Services', 'Private Banks', 'Large', 'INE095A01012'),
('TATASTEEL', 'Tata Steel Ltd', 'Metals & Mining', 'Iron & Steel', 'Large', 'INE081A01012'),

-- Additional Mid Cap Stocks (Popular ones)
('PIDILITIND', 'Pidilite Industries Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE318A01026'),
('GODREJCP', 'Godrej Consumer Products Ltd', 'Consumer Staples', 'FMCG - Household Products', 'Mid', 'INE102D01028'),
('DABUR', 'Dabur India Ltd', 'Consumer Staples', 'FMCG - Foods', 'Mid', 'INE016A01026'),
('HAVELLS', 'Havells India Ltd', 'Consumer Discretionary', 'Consumer Electronics', 'Mid', 'INE176B01034'),
('BERGEPAINT', 'Berger Paints India Ltd', 'Consumer Discretionary', 'Paints & Varnishes', 'Mid', 'INE463A01038'),
('ICICIPRULI', 'ICICI Prudential Life Insurance Co Ltd', 'Financial Services', 'Life Insurance', 'Mid', 'INE726G01019'),
('MCDOWELL-N', 'United Spirits Ltd', 'Consumer Staples', 'Alcoholic Beverages', 'Mid', 'INE854D01024'),
('SIEMENS', 'Siemens Ltd', 'Capital Goods', 'Heavy Electrical Equipment', 'Mid', 'INE003A01024'),
('DMART', 'Avenue Supermarts Ltd', 'Consumer Discretionary', 'Retail - Department Stores', 'Mid', 'INE192R01011'),
('NAUKRI', 'Info Edge (India) Ltd', 'Services', 'Internet & Catalogue Retail', 'Mid', 'INE663F01024'),
('PAGEIND', 'Page Industries Ltd', 'Consumer Discretionary', 'Apparel & Accessories', 'Mid', 'INE761H01022'),
('TRENT', 'Trent Ltd', 'Consumer Discretionary', 'Retail - Department Stores', 'Mid', 'INE849A01020'),
('JUBLFOOD', 'Jubilant Foodworks Ltd', 'Consumer Discretionary', 'Restaurants', 'Mid', 'INE797F01020'),
('MOTHERSON', 'Motherson Sumi Systems Ltd', 'Consumer Discretionary', 'Auto Parts & Equipment', 'Mid', 'INE775A01035'),
('BOSCHLTD', 'Bosch Ltd', 'Consumer Discretionary', 'Auto Parts & Equipment', 'Mid', 'INE323A01026'),
('PGHH', 'Procter & Gamble Hygiene & Health Care Ltd', 'Consumer Staples', 'FMCG - Household Products', 'Mid', 'INE179A01014'),
('COLPAL', 'Colgate-Palmolive (India) Ltd', 'Consumer Staples', 'FMCG - Household Products', 'Mid', 'INE259A01022'),
('MARICO', 'Marico Ltd', 'Consumer Staples', 'FMCG - Personal Products', 'Mid', 'INE196A01026'),
('GILLETTE', 'Gillette India Ltd', 'Consumer Staples', 'FMCG - Personal Products', 'Mid', 'INE322A01036'),
('ABB', 'ABB India Ltd', 'Capital Goods', 'Heavy Electrical Equipment', 'Mid', 'INE117A01022'),
('AMBUJACEM', 'Ambuja Cements Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE079A01024'),
('ACC', 'ACC Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE012A01025'),
('GLAXO', 'Glaxosmithkline Pharmaceuticals Ltd', 'Healthcare', 'Pharmaceuticals', 'Mid', 'INE376A01025'),
('PFIZER', 'Pfizer Ltd', 'Healthcare', 'Pharmaceuticals', 'Mid', 'INE182A01018'),
('SANOFI', 'Sanofi India Ltd', 'Healthcare', 'Pharmaceuticals', 'Mid', 'INE058A01010'),
('JUBLPHARMA', 'Jubilant Pharmova Ltd', 'Healthcare', 'Pharmaceuticals', 'Mid', 'INE700A01033'),
('IIFL', 'IIFL Finance Ltd', 'Financial Services', 'NBFC - Diversified', 'Mid', 'INE530B01024'),
('LICHSGFIN', 'LIC Housing Finance Ltd', 'Financial Services', 'Housing Finance', 'Mid', 'INE115A01026'),
('PFC', 'Power Finance Corporation Ltd', 'Financial Services', 'Term Lending - Power', 'Mid', 'INE134E01011'),
('RECLTD', 'REC Ltd', 'Financial Services', 'Term Lending - Power', 'Mid', 'INE020B01018'),
('CANBK', 'Canara Bank', 'Financial Services', 'Public Banks', 'Mid', 'INE476A01014'),
('IOB', 'Indian Overseas Bank', 'Financial Services', 'Public Banks', 'Mid', 'INE565A01014'),
('UCOBANK', 'UCO Bank', 'Financial Services', 'Public Banks', 'Mid', 'INE691A01018'),
('CENTRALBK', 'Central Bank of India', 'Financial Services', 'Public Banks', 'Mid', 'INE483A01010'),
('BANKBARODA', 'Bank of Baroda', 'Financial Services', 'Public Banks', 'Mid', 'INE028A01039'),
('BANKINDIA', 'Bank of India', 'Financial Services', 'Public Banks', 'Mid', 'INE084A01016'),
('FEDERALBNK', 'Federal Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE171A01029'),
('AUBANK', 'AU Small Finance Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE949L01017'),
('BANDHANBNK', 'Bandhan Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE545U01014'),
('IDFCFIRSTB', 'IDFC First Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE092T01019'),
('KARURVYSYA', 'Karur Vysya Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE036D01018'),
('RBLBANK', 'RBL Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE976G01028'),
('CUB', 'City Union Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE475A01039'),
('J&KBANK', 'Jammu & Kashmir Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE168A01041'),
('KTKBANK', 'Karnataka Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE614B01017'),
('DCBBANK', 'DCB Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE503A01015'),
('TMB', 'Tamilnad Mercantile Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE668A01025'),
('CSBBANK', 'CSB Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE679A01013'),
('DEEPAKNTR', 'Deepak Nitrite Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE288B01029'),
('SRF', 'SRF Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE647A01010'),
('ATUL', 'Atul Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE100A01010'),
('NAVINFLUOR', 'Navin Fluorine International Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE048G01026'),
('ALKYLAMINE', 'Alkyl Amines Chemicals Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE150B01039'),
('BALAMINES', 'Balaji Amines Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE050E01027'),
('CLEAN', 'Clean Science and Technology Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE227W01023'),
('VINATIORGA', 'Vinati Organics Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE490A01029'),
('PIIND', 'PI Industries Ltd', 'Chemicals', 'Pesticides & Agrochemicals', 'Mid', 'INE603J01030'),
('ANURAS', 'Anupam Rasayan India Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE930X01014'),
('BASF', 'BASF India Ltd', 'Chemicals', 'Diversified Chemicals', 'Mid', 'INE373A01013'),
('TATACHEM', 'Tata Chemicals Ltd', 'Chemicals', 'Soda Ash', 'Mid', 'INE092A01019'),
('GUJFLUORO', 'Gujarat Fluorochemicals Ltd', 'Chemicals', 'Commodity Chemicals', 'Mid', 'INE509A01029'),
('LXCHEM', 'Laxmi Organic Industries Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE576A01029'),
('SOLARINDS', 'Solar Industries India Ltd', 'Chemicals', 'Explosives', 'Mid', 'INE328E01013'),
('AARTIIND', 'Aarti Industries Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE769A01020'),
('RCF', 'Rashtriya Chemicals & Fertilizers Ltd', 'Chemicals', 'Fertilizers', 'Mid', 'INE027A01015'),
('GSFC', 'Gujarat State Fertilizers & Chemicals Ltd', 'Chemicals', 'Fertilizers', 'Mid', 'INE026A01025'),
('CHAMBLFERT', 'Chambal Fertilizers & Chemicals Ltd', 'Chemicals', 'Fertilizers', 'Mid', 'INE085A01013'),
('NFL', 'National Fertilizers Ltd', 'Chemicals', 'Fertilizers', 'Mid', 'INE870D01012'),
('FACT', 'Fertilizers & Chemicals Travancore Ltd', 'Chemicals', 'Fertilizers', 'Mid', 'INE188A01015'),
('MFL', 'Madras Fertilizers Ltd', 'Chemicals', 'Fertilizers', 'Mid', 'INE314A01013'),
('PARADEEP', 'Paradeep Phosphates Ltd', 'Chemicals', 'Fertilizers', 'Mid', 'INE088C01015'),

-- IT Sector - Additional Stocks
('COFORGE', 'Coforge Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE591G01017'),
('LTTS', 'L&T Technology Services Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE010V01017'),
('MINDTREE', 'Mindtree Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE018I01017'),
('MPHASIS', 'Mphasis Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE356A01018'),
('PERSISTENT', 'Persistent Systems Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE262H01021'),
('LTIM', 'L&T Infotech Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE214T01019'),
('DATAPATTNS', 'Data Patterns (India) Ltd', 'IT', 'Electronic Components', 'Mid', 'INE0JQJ01017'),
('ZENSARTECH', 'Zensar Technologies Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE520A01027'),
('CYIENT', 'Cyient Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE136B01020'),
('FIRSTSOURC', 'Firstsource Solutions Ltd', 'IT', 'BPO', 'Mid', 'INE684B01018'),
('HEXAWARE', 'Hexaware Technologies Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE010J01024'),
('NIITTECH', 'NIIT Technologies Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE721A01024'),
('SONATSOFTW', 'Sonata Software Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE269A01021'),
('KPITTECH', 'KPIT Technologies Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE04I401011'),
('NEWGEN', 'Newgen Software Technologies Ltd', 'IT', 'Software Products', 'Mid', 'INE619B01017'),
('MASTEK', 'Mastek Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE759A01021'),
('BIRLASOFT', 'Birlasoft Ltd', 'IT', 'IT Services & Consulting', 'Mid', 'INE836A01035'),
('GLAND', 'Gland Pharma Ltd', 'Healthcare', 'Pharmaceuticals', 'Mid', 'INE068V01023'),
('BIOCON', 'Biocon Ltd', 'Healthcare', 'Biotechnology', 'Mid', 'INE376G01013'),
('LALPATHLAB', 'Dr Lal PathLabs Ltd', 'Healthcare', 'Healthcare - Diagnostics', 'Mid', 'INE600L01024'),
('METROPOLIS', 'Metropolis Healthcare Ltd', 'Healthcare', 'Healthcare - Diagnostics', 'Mid', 'INE112J01019'),
('MAXHEALTH', 'Max Healthcare Institute Ltd', 'Healthcare', 'Healthcare - Hospital Services', 'Mid', 'INE03HU01018'),
('NH', 'Narayana Hrudayalaya Ltd', 'Healthcare', 'Healthcare - Hospital Services', 'Mid', 'INE410P01011'),
('FORTIS', 'Fortis Healthcare Ltd', 'Healthcare', 'Healthcare - Hospital Services', 'Mid', 'INE061F01013'),
('KIMS', 'Krishna Institute of Medical Sciences Ltd', 'Healthcare', 'Healthcare - Hospital Services', 'Mid', 'INE967H01017'),
('ASTERDM', 'Aster DM Healthcare Ltd', 'Healthcare', 'Healthcare - Hospital Services', 'Mid', 'INE914V01019'),
('RAINBOW', 'Rainbow Children Medicare Ltd', 'Healthcare', 'Healthcare - Hospital Services', 'Mid', 'INE0G7L01019'),
('POLYCAB', 'Polycab India Ltd', 'Consumer Discretionary', 'Wires & Cables', 'Mid', 'INE455K01017'),
('KEI', 'KEI Industries Ltd', 'Consumer Discretionary', 'Wires & Cables', 'Mid', 'INE878B01027'),
('HBLPOWER', 'HBL Power Systems Ltd', 'Capital Goods', 'Batteries', 'Mid', 'INE871B01014'),
('EXIDEIND', 'Exide Industries Ltd', 'Consumer Discretionary', 'Auto Parts & Equipment', 'Mid', 'INE302A01020'),
('AMARAJABAT', 'Amara Raja Batteries Ltd', 'Consumer Discretionary', 'Auto Parts & Equipment', 'Mid', 'INE885A01032'),
('FINPIPE', 'Finolex Industries Ltd', 'Consumer Discretionary', 'Plastic Products', 'Mid', 'INE183A01024'),
('SUPREMEIND', 'Supreme Industries Ltd', 'Consumer Discretionary', 'Plastic Products', 'Mid', 'INE195A01016'),
('ASTRAL', 'Astral Ltd', 'Consumer Discretionary', 'Plastic Products', 'Mid', 'INE006I01046'),
('PRINCEPIPE', 'Prince Pipes and Fittings Ltd', 'Consumer Discretionary', 'Plastic Products', 'Mid', 'INE0JPC01018'),
('WELCORP', 'Welspun Corp Ltd', 'Construction', 'Construction - Steel', 'Mid', 'INE191B01025'),
('RATNAMANI', 'Ratnamani Metals & Tubes Ltd', 'Construction', 'Pipes', 'Mid', 'INE346B01018'),
('SWSOLAR', 'Sterling and Wilson Renewable Energy Ltd', 'Energy', 'Renewable Energy', 'Mid', 'INE00VM01010'),
('INOXWIND', 'Inox Wind Ltd', 'Energy', 'Renewable Energy', 'Mid', 'INE0JPG01012'),
('SUZLON', 'Suzlon Energy Ltd', 'Energy', 'Renewable Energy', 'Mid', 'INE040H01021'),
('BHEL', 'Bharat Heavy Electricals Ltd', 'Capital Goods', 'Heavy Electrical Equipment', 'Mid', 'INE257A01026'),
('CUMMINSIND', 'Cummins India Ltd', 'Capital Goods', 'Diesel Engines', 'Mid', 'INE298A01020'),
('GREAVESCOT', 'Greaves Cotton Ltd', 'Capital Goods', 'Diesel Engines', 'Mid', 'INE224A01026'),
('KIRLOSENG', 'Kirloskar Oil Engines Ltd', 'Capital Goods', 'Diesel Engines', 'Mid', 'INE146L01020'),
('THERMAX', 'Thermax Ltd', 'Capital Goods', 'Industrial Machinery', 'Mid', 'INE152A01029'),
('SKFINDIA', 'SKF India Ltd', 'Capital Goods', 'Ball Bearings', 'Mid', 'INE640A01023'),
('SCHAEFFLER', 'Schaeffler India Ltd', 'Capital Goods', 'Ball Bearings', 'Mid', 'INE513A01027'),
('TIMKEN', 'Timken India Ltd', 'Capital Goods', 'Ball Bearings', 'Mid', 'INE325A01013'),
('CGPOWER', 'CG Power and Industrial Solutions Ltd', 'Capital Goods', 'Heavy Electrical Equipment', 'Mid', 'INE067A01029'),
('SADBHAV', 'Sadbhav Engineering Ltd', 'Construction', 'Civil Construction', 'Mid', 'INE226H01026'),
('KNRCON', 'KNR Constructions Ltd', 'Construction', 'Civil Construction', 'Mid', 'INE634I01029'),
('HGINFRA', 'H.G. Infra Engineering Ltd', 'Construction', 'Civil Construction', 'Mid', 'INE0JS801013'),
('PSPPROJECT', 'PSP Projects Ltd', 'Construction', 'Civil Construction', 'Mid', 'INE204A01010'),
('CAPACITE', 'Capacit e Infraprojects Ltd', 'Construction', 'Civil Construction', 'Mid', 'INE264T01014'),
('WELSPUNIND', 'Welspun India Ltd', 'Consumer Discretionary', 'Textiles', 'Mid', 'INE192B01031'),
('ARVIND', 'Arvind Ltd', 'Consumer Discretionary', 'Textiles', 'Mid', 'INE034A01011'),
('TRIDENT', 'Trident Ltd', 'Consumer Discretionary', 'Textiles', 'Mid', 'INE064C01022'),
('RUCHIRA', 'Ruchira Papers Ltd', 'Consumer Discretionary', 'Paper & Paper Products', 'Small', 'INE803H01014'),
('JKPAPER', 'JK Paper Ltd', 'Consumer Discretionary', 'Paper & Paper Products', 'Mid', 'INE789E01012'),
('TNPL', 'Tamil Nadu Newsprint & Papers Ltd', 'Consumer Discretionary', 'Paper & Paper Products', 'Mid', 'INE107A01015'),
('BECTORFOOD', 'Mrs Bectors Food Specialities Ltd', 'Consumer Staples', 'Bakery Products', 'Mid', 'INE418P01012'),
('VENKY`S', 'Venky`s (India) Ltd', 'Consumer Staples', 'Poultry & Meat Products', 'Mid', 'INE398A01010'),
('GODREJAGRO', 'Godrej Agrovet Ltd', 'Consumer Staples', 'FMCG - Foods', 'Mid', 'INE541D01014'),
('AVANTIFEED', 'Avanti Feeds Ltd', 'Consumer Staples', 'Aquaculture', 'Mid', 'INE871C01038'),
('TANLA', 'Tanla Platforms Ltd', 'Services', 'Telecom - Equipment', 'Mid', 'INE483C01032'),
('NUVOCO', 'Nuvoco Vistas Corporation Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE118A01020'),
('STARCEMENT', 'Star Cement Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE0HLG01012'),
('ORIENTCEM', 'Orient Cement Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE876S01010'),
('RAMCOCEM', 'The Ramco Cements Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE331A01037'),
('HEIDELBERG', 'HeidelbergCement India Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE578A01017'),
('DALBHARAT', 'Dalmia Bharat Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE00R701025'),
('JKCEMENT', 'JK Cement Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE823G01014'),
('BIRLACORPN', 'Birla Corporation Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE340A01012'),
('SAFARI', 'Safari Industries (India) Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE139J01017'),
('KANSAINER', 'Kansai Nerolac Paints Ltd', 'Consumer Discretionary', 'Paints & Varnishes', 'Mid', 'INE531A01024'),
('JCHAC', 'Johnson Controls-Hitachi Air Conditioning India Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE0G7J01020'),
('HONAUT', 'Honeywell Automation India Ltd', 'Consumer Discretionary', 'Consumer Electronics', 'Mid', 'INE671A01010'),
('WHIRLPOOL', 'Whirlpool of India Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE716A01013'),
('VOLTAS', 'Voltas Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE226A01021'),
('BLUESTARCO', 'Blue Star Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE472A01039'),
('CARRIERAIR', 'Carrier Airconditioning & Refrigeration Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE131B01018'),
('IFBIND', 'IFB Industries Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE559A01020'),
('IFCI', 'IFCI Ltd', 'Financial Services', 'Term Lending Institutions', 'Small', 'INE039A01010'),
('J&KBANK', 'Jammu & Kashmir Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE168A01041'),
('KTKBANK', 'Karnataka Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE614B01017'),
('DCBBANK', 'DCB Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE503A01015'),
('TMB', 'Tamilnad Mercantile Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE668A01025'),
('CSBBANK', 'CSB Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE679A01013'),
('FEDERALBNK', 'Federal Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE171A01029'),
('AUBANK', 'AU Small Finance Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE949L01017'),
('BANDHANBNK', 'Bandhan Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE545U01014'),
('IDFCFIRSTB', 'IDFC First Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE092T01019'),
('KARURVYSYA', 'Karur Vysya Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE036D01018'),
('RBLBANK', 'RBL Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE976G01028'),
('CUB', 'City Union Bank Ltd', 'Financial Services', 'Private Banks', 'Mid', 'INE475A01039'),

-- Additional Top Stocks by Sector (popular ones)
('VGUARD', 'V-Guard Industries Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE951I01027'),
('CROMPTON', 'Crompton Greaves Consumer Electricals Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE299U01018'),
('BAJAJELEC', 'Bajaj Electricals Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE193E01025'),
('SYMPHONY', 'Symphony Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Mid', 'INE225D01027'),
('KAJARIACER', 'Kajaria Ceramics Ltd', 'Consumer Discretionary', 'Ceramic Tiles', 'Mid', 'INE217B01036'),
('SOMANYCERA', 'Somany Ceramics Ltd', 'Consumer Discretionary', 'Ceramic Tiles', 'Mid', 'INE355A01028'),
('ORIENTBELL', 'Orient Bell Ltd', 'Consumer Discretionary', 'Ceramic Tiles', 'Mid', 'INE607D01018'),
('ADANIGREEN', 'Adani Green Energy Ltd', 'Energy', 'Renewable Energy', 'Large', 'INE364U01010'),
('ADANITRANS', 'Adani Transmission Ltd', 'Energy', 'Power - Transmission', 'Large', 'INE931S01020'),
('ATGL', 'Adani Total Gas Ltd', 'Energy', 'Gas Distribution', 'Mid', 'INE399L01023'),
('ADANIPOWER', 'Adani Power Ltd', 'Energy', 'Power Generation', 'Mid', 'INE814H01011'),
('TATAPOWER', 'Tata Power Company Ltd', 'Energy', 'Power Generation', 'Mid', 'INE245A01021'),
('TORNTPOWER', 'Torrent Power Ltd', 'Energy', 'Power Generation', 'Mid', 'INE813H01021'),
('JSWENERGY', 'JSW Energy Ltd', 'Energy', 'Power Generation', 'Mid', 'INE121E01018'),
('POWERGRID', 'Power Grid Corporation of India Ltd', 'Energy', 'Power - Transmission', 'Large', 'INE752E01010'),
('NTPC', 'NTPC Ltd', 'Energy', 'Power Generation', 'Large', 'INE733E01010'),
('NHPC', 'NHPC Ltd', 'Energy', 'Power Generation', 'Mid', 'INE848E01016'),
('SJVN', 'SJVN Ltd', 'Energy', 'Power Generation', 'Mid', 'INE075A01022'),
('GMRINFRA', 'GMR Airports Infrastructure Ltd', 'Infrastructure', 'Airport Services', 'Mid', 'INE776C01039'),
('IRB', 'IRB Infrastructure Developers Ltd', 'Infrastructure', 'Roads & Highways', 'Mid', 'INE821I01022'),
('MEP', 'MEP Infrastructure Developers Ltd', 'Infrastructure', 'Roads & Highways', 'Small', 'INE496B01019'),
('PNCINFRA', 'PNC Infratech Ltd', 'Infrastructure', 'Roads & Highways', 'Mid', 'INE0JJS01015'),
('HGINFRA', 'H.G. Infra Engineering Ltd', 'Infrastructure', 'Roads & Highways', 'Mid', 'INE0JS801013'),
('KNRCON', 'KNR Constructions Ltd', 'Infrastructure', 'Roads & Highways', 'Mid', 'INE634I01029'),
('ASHOKA', 'Ashoka Buildcon Ltd', 'Infrastructure', 'Roads & Highways', 'Mid', 'INE442H01029'),
('WELCORP', 'Welspun Corp Ltd', 'Infrastructure', 'Steel Pipes', 'Mid', 'INE191B01025'),
('BDL', 'Bharat Dynamics Ltd', 'Defense', 'Aerospace & Defense', 'Mid', 'INE0B7H01016'),
('HAL', 'Hindustan Aeronautics Ltd', 'Defense', 'Aerospace & Defense', 'Large', 'INE066F01020'),
('COCHINSHIP', 'Cochin Shipyard Ltd', 'Defense', 'Shipbuilding', 'Mid', 'INE0JQY01011'),
('GRSE', 'Garden Reach Shipbuilders & Engineers Ltd', 'Defense', 'Shipbuilding', 'Mid', 'INE0C7P01013'),
('MAZDOCK', 'Mazagon Dock Shipbuilders Ltd', 'Defense', 'Shipbuilding', 'Mid', 'INE0J0Z01020'),
('PARAS', 'Paras Defence and Space Technologies Ltd', 'Defense', 'Aerospace & Defense', 'Small', 'INE0C7K01014'),
('ZENTEC', 'Zen Technologies Ltd', 'Defense', 'Aerospace & Defense', 'Small', 'INE0H4H01025'),
('IDEA', 'Vodafone Idea Ltd', 'Telecom', 'Telecom - Cellular', 'Mid', 'INE669E01016'),
('TATACOMM', 'Tata Communications Ltd', 'Telecom', 'Telecom - Internet Service', 'Mid', 'INE151A01013'),
('ACCEL', 'Accel Ltd', 'Telecom', 'Telecom - Equipment', 'Small', 'INE0B0K01028'),
('INDUSTOWER', 'Indus Towers Ltd', 'Telecom', 'Telecom - Infrastructure', 'Mid', 'INE121J01017'),
('TEJASNET', 'Tejas Networks Ltd', 'Telecom', 'Telecom - Equipment', 'Mid', 'INE010J01025'),
('HFCL', 'HFCL Ltd', 'Telecom', 'Telecom - Equipment', 'Mid', 'INE548A01028'),
('ITI', 'ITI Ltd', 'Telecom', 'Telecom - Equipment', 'Mid', 'INE425A01027'),
('AIRTEL', 'Bharti Airtel Ltd', 'Telecom', 'Telecom - Cellular', 'Large', 'INE397D01024'),
('JIOFIN', 'Jio Financial Services Ltd', 'Financial Services', 'NBFC', 'Large', 'INE758E01017'),
('PAYTM', 'One 97 Communications Ltd', 'Services', 'Payment Gateway', 'Mid', 'INE0J8G01020'),
('POLICYBZR', 'PB Fintech Ltd', 'Services', 'Insurance Web Aggregator', 'Mid', 'INE417T01025'),
('ZOMATO', 'Zomato Ltd', 'Services', 'Online Food Delivery', 'Large', 'INE758T01015'),
('NYKAA', 'FSN E-Commerce Ventures Ltd', 'Services', 'Online Retail', 'Mid', 'INE0H7K01011'),
('INDIAMART', 'IndiaMART InterMESH Ltd', 'Services', 'B2B E-commerce', 'Mid', 'INE933S01016'),
('NAUKRI', 'Info Edge (India) Ltd', 'Services', 'Online Services', 'Mid', 'INE663F01024'),
('DELHIVERY', 'Delhivery Ltd', 'Services', 'Logistics', 'Mid', 'INE0KJX01019'),
('BLUEDART', 'Blue Dart Express Ltd', 'Services', 'Logistics', 'Mid', 'INE233B01017'),
('TCI', 'Transport Corporation of India Ltd', 'Services', 'Logistics', 'Mid', 'INE688A01022'),
('VRLLOG', 'VRL Logistics Ltd', 'Services', 'Logistics', 'Mid', 'INE760Y01010'),
('TV18BRDCST', 'TV18 Broadcast Ltd', 'Media', 'TV Broadcasting', 'Mid', 'INE886H01027'),
('SUNTV', 'Sun TV Network Ltd', 'Media', 'TV Broadcasting', 'Mid', 'INE424H01027'),
('ZEE', 'Zee Entertainment Enterprises Ltd', 'Media', 'TV Broadcasting', 'Mid', 'INE256A01028'),
('NETWORK18', 'Network18 Media & Investments Ltd', 'Media', 'TV Broadcasting', 'Mid', 'INE752H01013'),
('JUSTDIAL', 'Just Dial Ltd', 'Services', 'Online Services', 'Mid', 'INE599M01018'),
('SIS', 'SIS Ltd', 'Services', 'Security Services', 'Mid', 'INE285K01026'),
('CSLLTD', 'CSL Ltd', 'Services', 'Inspection & Certification', 'Small', 'INE0CO601016'),
('FINEORG', 'Fine Organic Industries Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE0J4N01019'),
('LAXMIMACH', 'Lakshmi Machine Works Ltd', 'Capital Goods', 'Textile Machinery', 'Mid', 'INE269B01029'),
('TATAELXSI', 'Tata Elxsi Ltd', 'IT', 'Software Products', 'Mid', 'INE670A01012'),
('MFL', 'Madras Fertilizers Ltd', 'Chemicals', 'Fertilizers', 'Small', 'INE314A01013'),
('ESABINDIA', 'Esab India Ltd', 'Capital Goods', 'Welding Equipment', 'Mid', 'INE284A01012'),
('WABAG', 'VA Tech Wabag Ltd', 'Construction', 'Water Treatment', 'Small', 'INE956G01038'),
('PHOENIXLTD', 'The Phoenix Mills Ltd', 'Real Estate', 'Real Estate - Commercial', 'Mid', 'INE211B01039'),
('DLF', 'DLF Ltd', 'Real Estate', 'Real Estate - Residential', 'Large', 'INE271C01023'),
('OBEROIRLTY', 'Oberoi Realty Ltd', 'Real Estate', 'Real Estate - Residential', 'Mid', 'INE093I01017'),
('GODREJPROP', 'Godrej Properties Ltd', 'Real Estate', 'Real Estate - Residential', 'Large', 'INE484J01027'),
('BRIGADE', 'Brigade Enterprises Ltd', 'Real Estate', 'Real Estate - Residential', 'Mid', 'INE791I01019'),
('SOBHA', 'Sobha Ltd', 'Real Estate', 'Real Estate - Residential', 'Mid', 'INE241J01012'),
('PRESTIGE', 'Prestige Estates Projects Ltd', 'Real Estate', 'Real Estate - Residential', 'Mid', 'INE811K01011'),
('MAHLIFE', 'Mahindra Lifespace Developers Ltd', 'Real Estate', 'Real Estate - Residential', 'Mid', 'INE813A01018'),
('ANANTRAJ', 'Anant Raj Ltd', 'Real Estate', 'Real Estate - Residential', 'Mid', 'INE242C01024'),
('SUNTECK', 'Sunteck Realty Ltd', 'Real Estate', 'Real Estate - Residential', 'Mid', 'INE805D01026'),
('NESCO', 'Nesco Ltd', 'Real Estate', 'Real Estate - Commercial', 'Mid', 'INE912C01026'),
('GATI', 'Gati Ltd', 'Services', 'Logistics', 'Small', 'INE135B01012'),
('ALLCARGO', 'Allcargo Logistics Ltd', 'Services', 'Logistics', 'Mid', 'INE418H01029'),
('CONCOR', 'Container Corporation of India Ltd', 'Services', 'Logistics', 'Mid', 'INE111A01025'),
('GUJGASLTD', 'Gujarat Gas Ltd', 'Energy', 'Gas Distribution', 'Mid', 'INE844O01030'),
('IGL', 'Indraprastha Gas Ltd', 'Energy', 'Gas Distribution', 'Mid', 'INE203G01027'),
('MGL', 'Mahanagar Gas Ltd', 'Energy', 'Gas Distribution', 'Mid', 'INE002S01010'),
('ADANIGAS', 'Adani Total Gas Ltd', 'Energy', 'Gas Distribution', 'Mid', 'INE399L01023'),
('PETRONET', 'Petronet LNG Ltd', 'Energy', 'Oil & Gas - Refining', 'Mid', 'INE347G01014'),
('OIL', 'Oil India Ltd', 'Energy', 'Oil & Gas - Exploration', 'Mid', 'INE274J01014'),
('MRPL', 'Mangalore Refinery & Petrochemicals Ltd', 'Energy', 'Oil & Gas - Refining', 'Mid', 'INE103A01014'),
('CHENNPETRO', 'Chennai Petroleum Corporation Ltd', 'Energy', 'Oil & Gas - Refining', 'Small', 'INE178A01016'),
('HINDPETRO', 'Hindustan Petroleum Corporation Ltd', 'Energy', 'Oil & Gas - Refining', 'Mid', 'INE094A01015'),
('CASTROLIND', 'Castrol India Ltd', 'Energy', 'Lubricants', 'Mid', 'INE172A01027'),
('GULFPETRO', 'GP Petroleums Ltd', 'Energy', 'Lubricants', 'Small', 'INE635D01026'),
('FMGOETZE', 'Federal-Mogul Goetze (India) Ltd', 'Auto', 'Auto Parts & Equipment', 'Small', 'INE529A01010'),
('MUNJALAU', 'Munjal Showa Ltd', 'Auto', 'Auto Parts & Equipment', 'Small', 'INE577C01017'),
('JTEKTINDIA', 'Jtekt India Ltd', 'Auto', 'Auto Parts & Equipment', 'Small', 'INE201A01020'),
('GNA', 'GNA Axles Ltd', 'Auto', 'Auto Parts & Equipment', 'Small', 'INE0JX901014'),
('JAYSREETEA', 'Jayshree Tea & Chemicals Ltd', 'Consumer Staples', 'Tea & Coffee', 'Small', 'INE385A01027'),
('CCL', 'CCL Products (India) Ltd', 'Consumer Staples', 'Tea & Coffee', 'Small', 'INE421D01022'),
('TATACOFFEE', 'Tata Coffee Ltd', 'Consumer Staples', 'Tea & Coffee', 'Small', 'INE421A01028'),
('RUBYMILLS', 'The Ruby Mills Ltd', 'Consumer Discretionary', 'Textiles', 'Small', 'INE301D01028'),
('CENTURYTEX', 'Century Textiles & Industries Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE055A01016'),
('BIRLACORPN', 'Birla Corporation Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE340A01012'),
('NCLIND', 'NCL Industries Ltd', 'Construction', 'Cement & Cement Products', 'Small', 'INE732C01016'),
('SAGCEM', 'Sagar Cements Ltd', 'Construction', 'Cement & Cement Products', 'Small', 'INE229C01013'),
('ACC', 'ACC Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE012A01025'),
('AMBUJACEM', 'Ambuja Cements Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE079A01024'),
('ULTRACEMCO', 'UltraTech Cement Ltd', 'Construction', 'Cement & Cement Products', 'Large', 'INE481G01011'),
('SHREECEM', 'Shree Cement Ltd', 'Construction', 'Cement & Cement Products', 'Large', 'INE070A01015'),
('JKLAKSHMI', 'JK Lakshmi Cement Ltd', 'Construction', 'Cement & Cement Products', 'Mid', 'INE786A01032'),
('RAJESHPEX', 'RajeshExports Ltd', 'Consumer Discretionary', 'Diamond & Jewellery', 'Small', 'INE485B01027'),
('PCJEWELLER', 'PC Jeweller Ltd', 'Consumer Discretionary', 'Diamond & Jewellery', 'Mid', 'INE785M01013'),
('THANGAMAYL', 'Thangamayil Jewellery Ltd', 'Consumer Discretionary', 'Diamond & Jewellery', 'Small', 'INE217D01012'),
('KALYANKJIL', 'Kalyan Jewellers India Ltd', 'Consumer Discretionary', 'Diamond & Jewellery', 'Mid', 'INE303R01014'),
('GOACARBON', 'Goa Carbon Ltd', 'Energy', 'Carbon Black', 'Small', 'INE426A01014'),
('HIMATSEIDE', 'Himatsingka Seide Ltd', 'Consumer Discretionary', 'Textiles', 'Small', 'INE049A01027'),
('SPINEX', ' spun tekstyl Ltd', 'Consumer Discretionary', 'Textiles', 'Small', 'INE0DY901010'),
('GUJFLUORO', 'Gujarat Fluorochemicals Ltd', 'Chemicals', 'Chemicals', 'Mid', 'INE509A01029'),
('LXCHEM', 'Laxmi Organic Industries Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE576A01029'),
('CLEAN', 'Clean Science and Technology Ltd', 'Chemicals', 'Specialty Chemicals', 'Mid', 'INE227W01023'),
('GANESHBE', 'Ganesh Benzoplast Ltd', 'Chemicals', 'Chemicals', 'Small', 'INE0C9B01013'),
('VIKASWSP', 'Vikas WSP Ltd', 'Chemicals', 'Guar Gum', 'Small', 'INE806A01012'),
('SMARTLINK', 'Smartlink Holdings Ltd', 'IT', 'IT Hardware', 'Small', 'INE178C01020'),
('KUANTUM', 'Kuantum Papers Ltd', 'Consumer Discretionary', 'Paper & Paper Products', 'Small', 'INE529E01014'),
('STERTOOLS', 'Sterling Tools Ltd', 'Auto', 'Auto Parts & Equipment', 'Small', 'INE334A01023'),
('RATNAMANI', 'Ratnamani Metals & Tubes Ltd', 'Construction', 'Pipes', 'Mid', 'INE346B01018'),
('SHEELAFOAM', 'Sheela Foam Ltd', 'Consumer Discretionary', 'Consumer Durables', 'Small', 'INE665L01035'),
('KINGFA', 'Kingfa Science & Technology (India) Ltd', 'Consumer Discretionary', 'Plastic Products', 'Small', 'INE0H7601018'),
('XPROINDIA', 'Xpro India Ltd', 'Consumer Discretionary', 'Plastic Products', 'Small', 'INE445C01023'),
('SUPREMEIND', 'Supreme Industries Ltd', 'Consumer Discretionary', 'Plastic Products', 'Mid', 'INE195A01016'),
('PRINCEPIPE', 'Prince Pipes and Fittings Ltd', 'Consumer Discretionary', 'Plastic Products', 'Mid', 'INE0JPC01018'),
('FINPIPE', 'Finolex Industries Ltd', 'Consumer Discretionary', 'Plastic Products', 'Mid', 'INE183A01024'),
('ASTRAL', 'Astral Ltd', 'Consumer Discretionary', 'Plastic Products', 'Mid', 'INE006I01046'),
('MAYURUNIQ', 'Mayur Uniquoters Ltd', 'Consumer Discretionary', 'Leather & Leather Products', 'Small', 'INE040D01038'),
('FUTURELIFESTYLE', 'Future Lifestyle Fashions Ltd', 'Consumer Discretionary', 'Retail', 'Small', 'INE452G01016'),
('BATAINDIA', 'Bata India Ltd', 'Consumer Discretionary', 'Footwear', 'Mid', 'INE176A01028'),
('METROBRAND', 'Metro Brands Ltd', 'Consumer Discretionary', 'Footwear', 'Mid', 'INE0EK701020'),
('Relaxo', 'Relaxo Footwears Ltd', 'Consumer Discretionary', 'Footwear', 'Mid', 'INE131B01039'),
('LIBERTSHOE', 'Liberty Shoes Ltd', 'Consumer Discretionary', 'Footwear', 'Small', 'INE557B01021'),
('TCPLPACK', 'TCPL Packaging Ltd', 'Consumer Discretionary', 'Packaging', 'Small', 'INE0COE01013'),
('Uflex', 'Uflex Ltd', 'Consumer Discretionary', 'Packaging', 'Mid', 'INE516A01017'),
('VSTIND', 'VST Industries Ltd', 'Consumer Staples', 'FMCG - Cigarettes', 'Small', 'INE710A01016'),
('GPI', 'GPI Ltd', 'Consumer Staples', 'Pharmaceuticals', 'Small', 'INE065A01023'),
('TANLA', 'Tanla Platforms Ltd', 'Telecom', 'Telecom Services', 'Mid', 'INE483C01032'),
('ACL', 'Andhra Cements Ltd', 'Construction', 'Cement & Cement Products', 'Small', 'INE666E01012'),
('DECCAN', 'Deccan Cements Ltd', 'Construction', 'Cement & Cement Products', 'Small', 'INE583C01021'),
('BHRTIARTL', 'Bharti Airtel Ltd', 'Telecom', 'Telecom Services', 'Large', 'INE397D01024'),
('IDEA', 'Vodafone Idea Ltd', 'Telecom', 'Telecom Services', 'Mid', 'INE669E01016'),
('TATACOMM', 'Tata Communications Ltd', 'Telecom', 'Telecom Services', 'Mid', 'INE151A01013'),
('ONMOBILE', 'OnMobile Global Ltd', 'Telecom', 'Telecom Services', 'Small', 'INE871D01019'),
('MTNL', 'Mahanagar Telephone Nigam Ltd', 'Telecom', 'Telecom Services', 'Small', 'INE153A01019'),
('RAILTEL', 'Railtel Corporation of India Ltd', 'Telecom', 'Telecom Infrastructure', 'Mid', 'INE0DD701013'),
('BSL', 'BSL Ltd', 'Consumer Discretionary', 'Textiles', 'Small', 'INE594B01012'),
('SUMEETIND', 'Sumeet Industries Ltd', 'Consumer Discretionary', 'Textiles', 'Small', 'INE235C01010'),
('KAKATCEM', 'Kakatiya Cement Sugar & Industries Ltd', 'Construction', 'Cement & Cement Products', 'Small', 'INE437C01015'),
('SAKSOFT', 'Saksoft Ltd', 'IT', 'IT Services', 'Small', 'INE667A01017'),
('RSYSTEMS', 'R Systems International Ltd', 'IT', 'IT Services', 'Small', 'INE411A01020'),
('MASTEK', 'Mastek Ltd', 'IT', 'IT Services', 'Mid', 'INE759A01021'),
('BIRLASOFT', 'Birlasoft Ltd', 'IT', 'IT Services', 'Mid', 'INE836A01035'),
('INTELLECT', 'Intellect Design Arena Ltd', 'IT', 'IT Services', 'Small', 'INE306R01017'),
('SONATSOFTW', 'Sonata Software Ltd', 'IT', 'IT Services', 'Mid', 'INE269A01021'),
('GSS', 'GSS Infotech Ltd', 'IT', 'IT Services', 'Small', 'INE0AAO01010'),
('IZMO', 'IZMO Ltd', 'IT', 'IT Services', 'Small', 'INE0H2601010'),
('SUBEX', 'Subex Ltd', 'IT', 'IT Services', 'Small', 'INE754A01014'),
('PRICOLLTD', 'Pricol Ltd', 'Auto', 'Auto Parts & Equipment', 'Small', 'INE726V01018'),
('AUTOLITIND', 'Autolite (India) Ltd', 'Auto', 'Auto Parts & Equipment', 'Small', 'INE448B01029'),
('SHREYAS', 'Shreyas Shipping & Logistics Ltd', 'Services', 'Shipping', 'Small', 'INE011A01019'),
('SEAMECLTD', 'Seamec Ltd', 'Energy', 'Oil & Gas Services', 'Small', 'INE497A01020'),
('SCI', 'Shipping Corporation of India Ltd', 'Services', 'Shipping', 'Small', 'INE315A01022'),
('GESHIP', 'Great Eastern Shipping Company Ltd', 'Services', 'Shipping', 'Mid', 'INE017A01032'),
('MERCATOR', 'Mercator Ltd', 'Services', 'Shipping', 'Small', 'INE614A01019'),
('TATAADVANCED', 'Tata Advanced Systems Ltd', 'Defense', 'Aerospace & Defense', 'Mid', 'INE0CQ101020'),
('DATAMATICS', 'Datamatics Global Services Ltd', 'IT', 'IT Services', 'Small', 'INE369A01021'),
('NEWGEN', 'Newgen Software Technologies Ltd', 'IT', 'IT Services', 'Mid', 'INE619B01017'),
('ECLERX', 'eClerx Services Ltd', 'IT', 'IT Services', 'Small', 'INE738I01010'),
('FIRSTSOURC', 'Firstsource Solutions Ltd', 'IT', 'IT Services', 'Small', 'INE684B01018'),
('ZENSARTECH', 'Zensar Technologies Ltd', 'IT', 'IT Services', 'Mid', 'INE520A01027'),
('TATAELXSI', 'Tata Elxsi Ltd', 'IT', 'IT Services', 'Mid', 'INE670A01012')
  ) AS v(symbol, name, sector, industry, market_cap_category, isin_code)
)
INSERT INTO stock_symbols (symbol, name, sector, industry, market_cap_category, isin_code)
SELECT
  symbol, name, sector, industry, market_cap_category, isin_code
FROM src
ON CONFLICT (symbol) DO UPDATE SET
  name = EXCLUDED.name,
  sector = EXCLUDED.sector,
  industry = EXCLUDED.industry,
  market_cap_category = EXCLUDED.market_cap_category,
  isin_code = EXCLUDED.isin_code,
  updated_at = now();

-- 4. Function to search stocks
CREATE OR REPLACE FUNCTION search_stocks(search_query TEXT)
RETURNS TABLE (
    symbol TEXT,
    name TEXT,
    sector TEXT,
    market_cap_category TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        s.symbol,
        s.name,
        s.sector,
        s.market_cap_category
    FROM stock_symbols s
    WHERE s.is_active = TRUE
        AND (
            s.symbol ILIKE '%' || search_query || '%'
            OR s.name ILIKE '%' || search_query || '%'
            OR s.sector ILIKE '%' || search_query || '%'
        )
    ORDER BY 
        CASE 
            WHEN s.symbol ILIKE search_query || '%' THEN 1
            WHEN s.name ILIKE search_query || '%' THEN 2
            ELSE 3
        END,
        s.market_cap_category = 'Large' DESC,
        s.symbol
    LIMIT 20;
END;
$$ LANGUAGE plpgsql;
